### ISSUE TITLE
Feature/Json email tokens

### ISSUE THREAD

**Issue by kimlisa** [hwsc-org/hwsc-user-svc#108]
## Description
As a developer, I want to create Jet's (json email token) using utilities from `hwsc-lib`

## Definitions of Done

- ~~[ ] Update the db schema~~
- [x] Update CreateUser to make this email token
- [x] Update VerifyEmailToken to lock using UUID extracted from the email token
- ~~[ ] Update db schema in `devops`~~

**Comment by faraonc** [comment]
Don't forget to also update hwsc-devops. Thanks!
