### ISSUE TITLE
Feature/fork github repo ulid

### ISSUE THREAD

**Issue by kimlisa** [hwsc-org/hwsc-user-svc#5]
## Description
As a developer, I want my user unique ID characters to be generated in lowercase. Fork [ulid](https://godoc.org/github.com/oklog/ulid) to change default uppercase character output to lowercase output. Or ask the repo developer to add in feature for choosing uppercase or lowercase generation.

## Definitions of Done

- [ ] generate UUID with lowercase characters

**Comment by faraonc** [comment]
Since _Account Registration_ is not common. Generation of UUID will use [ToLower](https://golang.org/pkg/strings/#ToLower)
