### ISSUE TITLE
Feature/return specific rpc code errors

### ISSUE THREAD

**Issue by kimlisa** [hwsc-org/hwsc-user-svc#85]
## Description
As a developer, I want to return rpc code specific to the error to provide consistency in error decoding in front end and back end.

Requires refactoring everything that returns errors including unit tests and integration tests.

## Definitions of Done

- [ ] rpc codes are specific to error
- [ ] unit tested to ensure test passes
- [ ] integration tested to ensure test passes

**Comment by faraonc** [comment]
Closing this to follow https://jbrandhorst.com/post/grpc-errors/
